### ISSUE TITLE
Añadir los eventos scrapeados desde el script de Python

### ISSUE THREAD

**Issue by josexs** [XSMusic/xsmusic-backend#78]
```[tasklist]
### Tasks
- [x] Añadir artistas al evento
- [x] Añadir evento a db
- [x] Crear funcion para llamar a archivo python
```
